// ---------------------------------------------------------------
// Topic data — 32 topics, Beginner -> Advanced, English + Tamil
// ---------------------------------------------------------------
const TOPICS = [
  { id: 1, en: "Parts of Speech", ta: "சொல் வகைகள்", level: "Beginner" },
  { id: 2, en: "Sentence Structure", ta: "வாக்கிய அமைப்பு", level: "Beginner" },
  { id: 3, en: "Nouns", ta: "பெயர்ச்சொல்", level: "Beginner" },
  { id: 4, en: "Pronouns", ta: "பிரதிப்பெயர்ச்சொல்", level: "Beginner" },
  { id: 5, en: "Verbs", ta: "வினைச்சொல்", level: "Beginner" },
  { id: 6, en: "Subject–Verb Agreement", ta: "எழுவாய்-வினை ஒற்றுமை", level: "Beginner" },
  { id: 7, en: "Tenses (12)", ta: "காலங்கள் (12)", level: "Beginner" },
  { id: 8, en: "Articles", ta: "Articles (a, an, the)", level: "Beginner" },
  { id: 9, en: "Determiners", ta: "நிர்ணயிப்பான்கள்", level: "Beginner" },
  { id: 10, en: "Adjectives", ta: "பெயரடை", level: "Intermediate" },
  { id: 11, en: "Adverbs", ta: "வினையடை", level: "Intermediate" },
  { id: 12, en: "Prepositions", ta: "முன்னிடைச்சொல்", level: "Intermediate" },
  { id: 13, en: "Conjunctions", ta: "இணைப்புச்சொல்", level: "Intermediate" },
  { id: 14, en: "Phrases", ta: "தொடர்கள்", level: "Intermediate" },
  { id: 15, en: "Clauses", ta: "உட்பிரிவுகள்", level: "Intermediate" },
  { id: 16, en: "Active & Passive Voice", ta: "செய்வினை & செயப்பாட்டு வினை", level: "Intermediate" },
  { id: 17, en: "Direct & Indirect Speech", ta: "நேரடி & மறைமுக பேச்சு", level: "Intermediate" },
  { id: 18, en: "Modals", ta: "இயல்பு துணை வினைகள்", level: "Intermediate" },
  { id: 19, en: "Conditionals", ta: "நிபந்தனை வாக்கியங்கள்", level: "Intermediate" },
  { id: 20, en: "Gerunds, Infinitives & Participles", ta: "வினையெச்சம் & தொழிற்பெயர்", level: "Intermediate" },
  { id: 21, en: "Question Tags", ta: "கேள்வி ஏற்பு சொற்கள்", level: "Advanced" },
  { id: 22, en: "Punctuation", ta: "நிறுத்தற்குறிகள்", level: "Advanced" },
  { id: 23, en: "Capitalization", ta: "பெரிய எழுத்து பயன்பாடு", level: "Advanced" },
  { id: 24, en: "Common Grammar Errors", ta: "பொதுவான இலக்கண பிழைகள்", level: "Advanced" },
  { id: 25, en: "Advanced Grammar", ta: "மேம்பட்ட இலக்கணம்", level: "Advanced" },
  { id: 26, en: "Business & Academic English", ta: "வணிக & கல்வி ஆங்கிலம்", level: "Advanced" },
  { id: 27, en: "Writing Skills", ta: "எழுத்துத் திறன்கள்", level: "Advanced" },
  { id: 28, en: "Spoken English Practice", ta: "பேச்சு ஆங்கில பயிற்சி", level: "Advanced" },
  { id: 29, en: "Phrasal Verbs", ta: "மொழிப்புணர்ச்சி வினைச்சொற்கள்", level: "Advanced" },
  { id: 30, en: "Public Speaking", ta: "பொதுப் பேச்சு", level: "Advanced" },
  { id: 31, en: "Voice Practice", ta: "குரல் பயிற்சி", level: "Advanced" },
  { id: 32, en: "Professional Self Intro", ta: "தொழில்முறை சுய அறிமுகம்", level: "Advanced" },
];

const GROUPS = ["Beginner", "Intermediate", "Advanced"];
const PUBLIC_SPEAKING_TOPIC_ID = 30;
const VOICE_PRACTICE_TOPIC_ID = 31;
const PROFESSIONAL_INTRO_TOPIC_ID = 32;

// ---------------------------------------------------------------
// Verb of the Day — a fresh, random, advanced/professional verb is
// generated by the Groq model each time (see api/verb.js), not a fixed
// local list. Capped at MAX_VERB_REFRESHES new verbs per day.
// ---------------------------------------------------------------
const MAX_VERB_REFRESHES = 10;

// ---------------------------------------------------------------
// State
// ---------------------------------------------------------------
let currentTopic = null;
let conversations = loadProgress().conversations || {}; // { topicId: [{role, content}] }
let completed = new Set(loadProgress().completed || []);
let apiKeyVerified = false;

// ---------------------------------------------------------------
// Groq API key box (sidebar): save, verify, gate chat on it
// ---------------------------------------------------------------
const apiKeyInput = document.getElementById("apiKeyInput");
const verifyKeyBtn = document.getElementById("verifyKeyBtn");
const keyStatusEl = document.getElementById("keyStatus");

function getStoredKey() {
  try {
    return localStorage.getItem("groqApiKey") || "";
  } catch {
    return "";
  }
}

function setStoredKey(key) {
  try {
    localStorage.setItem("groqApiKey", key);
  } catch {}
}

function setKeyStatus(text, kind) {
  keyStatusEl.textContent = text;
  keyStatusEl.className = "key-status" + (kind ? ` ${kind}` : "");
}

async function verifyKey(key, { silent = false } = {}) {
  if (!key) {
    apiKeyVerified = false;
    if (!silent) setKeyStatus("Not connected yet.", "");
    return false;
  }
  if (!silent) {
    setKeyStatus("Checking with Groq…", "pending");
    verifyKeyBtn.disabled = true;
  }
  try {
    const res = await fetch("/api/verify", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ apiKey: key }),
    });
    const data = await res.json();
    if (data.valid) {
      apiKeyVerified = true;
      setStoredKey(key);
      setKeyStatus("Connected — ready to chat.", "ok");
      return true;
    } else {
      apiKeyVerified = false;
      setKeyStatus(data.error || "Couldn't verify this key.", "err");
      return false;
    }
  } catch (err) {
    apiKeyVerified = false;
    setKeyStatus("Couldn't reach the server to verify. Try again.", "err");
    return false;
  } finally {
    verifyKeyBtn.disabled = false;
  }
}

verifyKeyBtn.addEventListener("click", () => {
  const key = apiKeyInput.value.trim();
  verifyKey(key);
});

apiKeyInput.addEventListener("keydown", (e) => {
  if (e.key === "Enter") {
    e.preventDefault();
    verifyKeyBtn.click();
  }
});

// On load: if a key was saved earlier, fill it in and quietly re-verify
(function initKey() {
  const saved = getStoredKey();
  if (saved) {
    apiKeyInput.value = saved;
    setKeyStatus("Re-checking saved key…", "pending");
    verifyKey(saved, { silent: false });
  }
})();

function loadProgress() {
  try {
    const raw = localStorage.getItem("teach-progress");
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function saveProgress() {
  try {
    localStorage.setItem(
      "teach-progress",
      JSON.stringify({ conversations, completed: [...completed] })
    );
  } catch {}
}

// ---------------------------------------------------------------
// Sidebar rendering
// ---------------------------------------------------------------
const topicPathEl = document.getElementById("topicPath");

function renderSidebar() {
  topicPathEl.innerHTML = "";
  GROUPS.forEach((group) => {
    const label = document.createElement("div");
    label.className = "path-group-label";
    label.textContent = group;
    topicPathEl.appendChild(label);

    TOPICS.filter((t) => t.level === group).forEach((t) => {
      const btn = document.createElement("button");
      btn.className = "topic-btn" + (t.id === currentTopic?.id ? " active" : "") + (completed.has(t.id) ? " done" : "");
      btn.innerHTML = `<span class="num">${String(t.id).padStart(2, "0")}</span><span>${t.en}</span>`;
      btn.addEventListener("click", () => selectTopic(t.id));
      topicPathEl.appendChild(btn);
    });
  });
  updateProgressBar();
}

function updateProgressBar() {
  document.getElementById("progressCount").textContent = `${completed.size} / 32`;
  document.getElementById("progressFill").style.width = `${(completed.size / 32) * 100}%`;
}

// ---------------------------------------------------------------
// Topic selection
// ---------------------------------------------------------------
const heroEl = document.getElementById("hero");
const topicViewEl = document.getElementById("topicView");
const verbViewEl = document.getElementById("verbView");
const verbNavBtn = document.getElementById("verbNavBtn");
const chatThreadEl = document.getElementById("chatThread");

function selectTopic(id) {
  const topic = TOPICS.find((t) => t.id === id);
  if (!topic) return;
  if (isRecording) stopRecording();
  currentTopic = topic;
  completed.add(id);
  saveProgress();

  heroEl.hidden = true;
  topicViewEl.hidden = false;
  verbViewEl.hidden = true;
  verbNavBtn.classList.remove("active");

  document.getElementById("topicId").textContent = String(topic.id).padStart(2, "0");
  document.getElementById("topicEn").textContent = topic.en;
  document.getElementById("topicTa").textContent = topic.ta;
  document.getElementById("topicLevel").textContent = topic.level;

  const isVoiceTopic = topic.id === VOICE_PRACTICE_TOPIC_ID;
  chatForm.hidden = isVoiceTopic;
  if (voiceControlsEl) voiceControlsEl.hidden = !isVoiceTopic;
  const chatHintEl = document.getElementById("chatHint");
  if (chatHintEl) chatHintEl.hidden = isVoiceTopic;

  renderSidebar();
  renderChat();

  if (!conversations[id] || conversations[id].length === 0) {
    conversations[id] = [];
    if (!apiKeyVerified) {
      appendMessage(
        "bot",
        "**Add your free Groq API key** in the box on the left, then click **Verify**, to start this lesson.\n\n(இடதுபுறம் உள்ள பெட்டியில் உங்கள் இலவச Groq திறவுகோலைச் சேர்த்து 'Verify' அழுத்தவும்.)"
      );
      // Not saved into conversations[id] on purpose — once the key is
      // verified, selecting this topic again will still trigger the real intro.
    } else if (topic.id === PUBLIC_SPEAKING_TOPIC_ID) {
      // Public Speaking works differently: ask the learner for a subject first,
      // instead of auto-generating an introduction.
      appendMessage(
        "bot",
        "**Type any topic** you'd like a public speaking passage on — e.g. \"leadership\", \"climate change\", \"my school\".\n\nI'll share 10–20 lines, with the important verbs in **bold** and their Tamil meaning right after in brackets.\n\n(நீங்கள் பேச விரும்பும் தலைப்பை தட்டச்சு செய்யவும் — எ.கா. \"தலைமைத்துவம்\". முக்கியமான வினைச்சொற்கள் **தடிமனாக** காட்டப்பட்டு, அதற்கடுத்து அதன் தமிழ் அர்த்தம் அடைப்புக்குறிக்குள் தரப்படும்.)"
      );
    } else if (topic.id === VOICE_PRACTICE_TOPIC_ID) {
      // Voice Practice works by mic, not typing: explain the flow up front.
      appendMessage(
        "bot",
        "**Tap the mic button below and speak a sentence** — in English, or mixed with Tamil, whatever feels natural. I'll correct the grammar and tone, and you can tap **Play** on my reply to hear the correct version spoken aloud.\n\n(கீழே உள்ள மைக் பொத்தானைத் தட்டி ஒரு வாக்கியம் பேசுங்கள். நான் இலக்கணத்தையும் தொனியையும் திருத்துவேன்.)"
      );
    } else if (topic.id === PROFESSIONAL_INTRO_TOPIC_ID) {
      // Professional Self Intro works like a mock interview: ask for the
      // learner's profession first, then run an escalating Q&A, correcting
      // each answer, instead of auto-generating an introduction.
      appendMessage(
        "bot",
        "**Type your profession or job role** — e.g. \"software engineer\", \"nurse\", \"final-year student\", \"sales executive\".\n\nI'll run this like a real interview: starting with **\"Tell me about yourself\"**, then asking questions that get more advanced each time. Whenever you answer, I'll correct your English first, then ask the next question.\n\n(உங்கள் தொழில் அல்லது வேலையை தட்டச்சு செய்யவும். ஒரு நேர்காணல் போல கேள்விகள் கேட்பேன், உங்கள் பதில்களை திருத்துவேன்.)"
      );
    } else {
      // Kick off with an automatic introduction from the tutor
      sendToTutor(`Please introduce the topic "${topic.en}" to a Tamil-speaking beginner/intermediate English learner. Give a short, simple explanation with 2-3 real-time example sentences in English, each with its Tamil meaning.`, { silent: true });
    }
  }

  document.getElementById("sidebar").classList.remove("open");
}

document.getElementById("startBtn").addEventListener("click", () => selectTopic(1));

// ---------------------------------------------------------------
// Chat rendering
// ---------------------------------------------------------------
function renderChat() {
  chatThreadEl.innerHTML = "";
  const msgs = conversations[currentTopic.id] || [];
  msgs.forEach((m) => appendMessage(m.role, m.content, false));
  chatThreadEl.scrollTop = chatThreadEl.scrollHeight;
}

function appendMessage(role, content, scroll = true) {
  const wrap = document.createElement("div");
  wrap.className = `msg ${role}`;
  const bubble = document.createElement("div");
  bubble.className = "bubble";
  bubble.innerHTML = formatContent(content);
  wrap.appendChild(bubble);

  if (role === "bot" && currentTopic?.id === VOICE_PRACTICE_TOPIC_ID) {
    const speakBtn = document.createElement("button");
    speakBtn.type = "button";
    speakBtn.className = "speak-btn";
    speakBtn.textContent = "🔊 Play";
    speakBtn.addEventListener("click", () => speakText(content));
    wrap.appendChild(speakBtn);
  }

  chatThreadEl.appendChild(wrap);
  if (scroll) chatThreadEl.scrollTop = chatThreadEl.scrollHeight;
  return wrap;
}

// Very small formatter: turns **bold**, `code`, and Tamil-detected lines into styled markup
function formatContent(text) {
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  const withInline = escaped
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`(.+?)`/g, "<code>$1</code>");

  const paragraphs = withInline.split(/\n{2,}/).map((block) => {
    const isTamil = /[\u0B80-\u0BFF]/.test(block) && !/[a-zA-Z]{3,}/.test(block.replace(/\(.*?\)/g, ""));
    const lines = block.split(/\n/).join("<br>");
    return `<p class="${isTamil ? "ta" : ""}">${lines}</p>`;
  });

  return paragraphs.join("");
}

// ---------------------------------------------------------------
// Talking to the tutor (calls our own /api/chat serverless function)
// ---------------------------------------------------------------
const chatForm = document.getElementById("chatForm");
const chatInput = document.getElementById("chatInput");
const sendBtn = document.getElementById("sendBtn");

chatForm.addEventListener("submit", (e) => {
  e.preventDefault();
  const text = chatInput.value.trim();
  if (!text || !currentTopic) return;
  chatInput.value = "";
  sendToTutor(text);
});

async function sendToTutor(userText, opts = {}) {
  const topic = currentTopic;

  if (!apiKeyVerified) {
    if (!opts.silent) {
      conversations[topic.id].push({ role: "user", content: userText });
      appendMessage("user", userText);
    }
    appendMessage(
      "bot",
      "**Add your free Groq API key** in the box on the left, then click **Verify**, before chatting.\n\n(முதலில் இடதுபுறம் Groq திறவுகோலைச் சேர்த்து 'Verify' அழுத்தவும்.)"
    );
    apiKeyInput.focus();
    return;
  }

  if (!opts.silent) {
    conversations[topic.id].push({ role: "user", content: userText });
    appendMessage("user", userText);
  }

  sendBtn.disabled = true;
  const typingEl = appendMessage("bot typing", "Typing…");

  try {
    const res = await fetch("/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        topic: { en: topic.en, ta: topic.ta, level: topic.level },
        message: userText,
        history: (conversations[topic.id] || []).slice(-10),
        apiKey: getStoredKey(),
      }),
    });

    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      typingEl.remove();
      if (data.error === "missing_key" || data.error === "invalid_key") {
        apiKeyVerified = false;
        setKeyStatus(data.message || "Your Groq key needs to be re-verified.", "err");
        appendMessage(
          "bot",
          `**${data.message || "Your Groq key needs to be re-verified."}**\n\n(உங்கள் திறவுகோலை மீண்டும் சரிபார்க்கவும்.)`
        );
      } else {
        appendMessage(
          "bot",
          "**Something went wrong** reaching the tutor. Please try again in a moment.\n\n(சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.)"
        );
      }
      return;
    }

    const reply = data.reply || "Sorry, I couldn't generate a reply just now. Please try again.";
    typingEl.remove();
    conversations[topic.id].push({ role: "bot", content: reply });
    appendMessage("bot", reply);
    saveProgress();
  } catch (err) {
    typingEl.remove();
    appendMessage(
      "bot",
      "**Connection error.** The tutor couldn't be reached — please check your internet connection and try again in a moment.\n\n(இணைப்பு பிழை — சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.)"
    );
    console.error(err);
  } finally {
    sendBtn.disabled = false;
  }
}

// ---------------------------------------------------------------
// Voice Practice: record -> transcribe (Groq Whisper) -> tutor correction
// ---------------------------------------------------------------
const micBtn = document.getElementById("micBtn");
const voiceStatusEl = document.getElementById("voiceStatus");
const voiceControlsEl = document.getElementById("voiceControls");

let mediaRecorder = null;
let recordedChunks = [];
let isRecording = false;
let autoStopTimer = null;
const MAX_RECORD_MS = 20000; // keep clips short so the base64 payload stays small

function setVoiceStatus(text) {
  if (voiceStatusEl) voiceStatusEl.textContent = text;
}

async function startRecording() {
  if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") {
    setVoiceStatus("Your browser doesn't support microphone recording. Try Chrome or Safari.");
    return;
  }
  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    recordedChunks = [];
    const mimeType = MediaRecorder.isTypeSupported("audio/webm") ? "audio/webm" : "audio/mp4";
    mediaRecorder = new MediaRecorder(stream, { mimeType });

    mediaRecorder.ondataavailable = (e) => {
      if (e.data.size > 0) recordedChunks.push(e.data);
    };
    mediaRecorder.onstop = () => {
      stream.getTracks().forEach((t) => t.stop());
      handleRecordingStop(mimeType);
    };

    mediaRecorder.start();
    isRecording = true;
    micBtn.classList.add("recording");
    micBtn.textContent = "⏹ Stop";
    setVoiceStatus("Listening… tap Stop when you're done. (20s max)");

    autoStopTimer = setTimeout(() => {
      if (isRecording) stopRecording();
    }, MAX_RECORD_MS);
  } catch (err) {
    console.error(err);
    setVoiceStatus("Couldn't access the microphone. Check browser permissions and try again.");
  }
}

function stopRecording() {
  if (!mediaRecorder || !isRecording) return;
  clearTimeout(autoStopTimer);
  isRecording = false;
  micBtn.classList.remove("recording");
  micBtn.textContent = "🎤 Tap to speak";
  mediaRecorder.stop();
}

async function handleRecordingStop(mimeType) {
  if (!currentTopic || currentTopic.id !== VOICE_PRACTICE_TOPIC_ID) return;

  if (!apiKeyVerified) {
    appendMessage(
      "bot",
      "**Add your free Groq API key** in the box on the left, then click **Verify**, before recording.\n\n(முதலில் இடதுபுறம் Groq திறவுகோலைச் சேர்த்து 'Verify' அழுத்தவும்.)"
    );
    return;
  }

  const blob = new Blob(recordedChunks, { type: mimeType });
  if (blob.size < 1000) {
    setVoiceStatus("That was too short — tap and speak a full sentence.");
    return;
  }

  setVoiceStatus("Transcribing…");
  micBtn.disabled = true;

  try {
    const audioBase64 = await blobToBase64(blob);
    const res = await fetch("/api/transcribe", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ audioBase64, mimeType, apiKey: getStoredKey() }),
    });
    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      if (data.error === "invalid_key") {
        apiKeyVerified = false;
        setKeyStatus(data.message || "Your Groq key needs to be re-verified.", "err");
      }
      setVoiceStatus(data.message || "Couldn't transcribe that — please try again.");
      return;
    }
    if (!data.text) {
      setVoiceStatus(data.message || "Didn't catch that — please try again.");
      return;
    }

    setVoiceStatus("Tap the mic to speak again.");
    sendToTutor(data.text);
  } catch (err) {
    console.error(err);
    setVoiceStatus("Connection error while transcribing. Try again.");
  } finally {
    micBtn.disabled = false;
  }
}

function blobToBase64(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result.split(",")[1]);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

if (micBtn) {
  micBtn.addEventListener("click", () => {
    if (isRecording) stopRecording();
    else startRecording();
  });
}

// Reads a bot reply aloud using the browser's built-in text-to-speech —
// no extra API needed. Strips markdown so it doesn't say "asterisk asterisk".
function speakText(text) {
  if (!("speechSynthesis" in window)) return;
  const plain = text.replace(/\*\*(.+?)\*\*/g, "$1").replace(/`(.+?)`/g, "$1");
  const utter = new SpeechSynthesisUtterance(plain);
  utter.lang = "en-IN";
  window.speechSynthesis.cancel();
  window.speechSynthesis.speak(utter);
}

// ---------------------------------------------------------------
// Verb of the Day: a fresh verb is generated by the tutor model (via
// api/verb.js) the first time it's opened each day, then cached. The
// learner can tap "New verb" to generate a different one, up to
// MAX_VERB_REFRESHES times per day (that daily count does NOT include
// the very first verb shown for the day).
// ---------------------------------------------------------------
const verbRefreshBtn = document.getElementById("verbRefreshBtn");
const verbRefreshCountEl = document.getElementById("verbRefreshCount");
const verbCardEl = document.getElementById("verbCard");

function todayKey() {
  const d = new Date();
  return `${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`;
}

function loadVerbState() {
  try {
    const raw = localStorage.getItem("verb-of-day");
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function saveVerbState() {
  try {
    localStorage.setItem("verb-of-day", JSON.stringify(verbState));
  } catch {}
}

let verbState = loadVerbState();
if (verbState.date !== todayKey()) {
  // New day (or first ever visit): reset the refresh count and the
  // shown-verbs history. The verb itself gets generated fresh on open.
  verbState = { date: todayKey(), refreshCount: 0, verb: null, shown: [] };
  saveVerbState();
}
let verbLoading = false;

function updateVerbRefreshLabel() {
  const remaining = Math.max(0, MAX_VERB_REFRESHES - verbState.refreshCount);
  verbRefreshCountEl.textContent =
    remaining > 0
      ? `${remaining} refresh${remaining === 1 ? "" : "es"} left today`
      : "No refreshes left — come back tomorrow";
  verbRefreshBtn.disabled = verbLoading || remaining <= 0;
}

function renderVerbCard(verb) {
  verbCardEl.classList.remove("loading", "error");
  document.getElementById("verbWordEn").textContent = verb.en;
  document.getElementById("verbWordTa").textContent = verb.ta || "";
  document.getElementById("verbMeaning").textContent = verb.meaning;
  document.getElementById("verbSentenceEn").textContent = verb.sentence;
  document.getElementById("verbSentenceTa").textContent = verb.sentenceTa || "";
  updateVerbRefreshLabel();
}

function renderVerbLoading() {
  verbCardEl.classList.remove("error");
  verbCardEl.classList.add("loading");
  document.getElementById("verbWordEn").textContent = "Loading…";
  document.getElementById("verbWordTa").textContent = "";
  document.getElementById("verbMeaning").textContent = "Fetching a new advanced verb for you…";
  document.getElementById("verbSentenceEn").textContent = "";
  document.getElementById("verbSentenceTa").textContent = "";
  verbRefreshBtn.disabled = true;
}

function renderVerbMessage(title, subtitle) {
  verbCardEl.classList.remove("loading");
  verbCardEl.classList.add("error");
  document.getElementById("verbWordEn").textContent = title;
  document.getElementById("verbWordTa").textContent = "";
  document.getElementById("verbMeaning").textContent = subtitle;
  document.getElementById("verbSentenceEn").textContent = "";
  document.getElementById("verbSentenceTa").textContent = "";
  updateVerbRefreshLabel();
}

async function fetchNewVerb({ isInitial = false } = {}) {
  if (verbState.date !== todayKey()) {
    verbState = { date: todayKey(), refreshCount: 0, verb: null, shown: [] };
    saveVerbState();
  }

  if (!isInitial && verbState.refreshCount >= MAX_VERB_REFRESHES) {
    updateVerbRefreshLabel();
    return;
  }
  if (!apiKeyVerified) {
    renderVerbMessage(
      "Add your Groq API key",
      "Add your free Groq API key in the sidebar, then click Verify, to generate today's verb."
    );
    return;
  }

  verbLoading = true;
  renderVerbLoading();

  try {
    const res = await fetch("/api/verb", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ apiKey: getStoredKey(), exclude: verbState.shown }),
    });
    const data = await res.json().catch(() => ({}));

    if (!res.ok || !data.verb) {
      if (data.error === "missing_key" || data.error === "invalid_key") {
        apiKeyVerified = false;
        setKeyStatus(data.message || "Your Groq key needs to be re-verified.", "err");
        renderVerbMessage("Key needs re-verifying", data.message || "Please re-verify your Groq key in the sidebar.");
      } else {
        renderVerbMessage("Couldn't load a verb", data.message || "Something went wrong. Please try again.");
      }
      return;
    }

    verbState.verb = data.verb;
    verbState.shown = [...(verbState.shown || []), data.verb.en].slice(-15);
    if (!isInitial) verbState.refreshCount += 1;
    saveVerbState();
    renderVerbCard(data.verb);
  } catch (err) {
    console.error(err);
    renderVerbMessage("Connection error", "Couldn't reach the server. Please check your connection and try again.");
  } finally {
    verbLoading = false;
    updateVerbRefreshLabel();
  }
}

function showVerbView() {
  if (isRecording) stopRecording();
  currentTopic = null;
  heroEl.hidden = true;
  topicViewEl.hidden = true;
  verbViewEl.hidden = false;
  renderSidebar(); // clears any "active" highlight on the topic list
  verbNavBtn.classList.add("active");
  document.getElementById("sidebar").classList.remove("open");

  if (verbState.verb) {
    renderVerbCard(verbState.verb);
  } else {
    fetchNewVerb({ isInitial: true });
  }
}

verbNavBtn.addEventListener("click", showVerbView);
verbRefreshBtn.addEventListener("click", () => fetchNewVerb({ isInitial: false }));

// ---------------------------------------------------------------
// Mobile sidebar toggle
// ---------------------------------------------------------------
document.getElementById("sidebarToggle").addEventListener("click", () => {
  document.getElementById("sidebar").classList.toggle("open");
});

// ---------------------------------------------------------------
// Init
// ---------------------------------------------------------------
renderSidebar();
